### ISSUE TITLE
Two sensors, not working.

### ISSUE THREAD

**Issue by jcroucher** [pcfens/RaspberryPi-AS3935#12] opened 2014-12-14 04:10 UTC
The first sensor is mine. 
It was incorrectly constantly sensing lightning when I had a fan going near the sensor. After disabling this fan I no longer picked up the false strikes. However 3 storms have passed over, including a strike that destroyed a tree a few streets away. Not a single strike has been detected.
I have checked the settings after each time and I cannot find anything obvious that would be wrong.
I broke the fan when removing it from the case so I cannot see if this will trigger the sensor again.
The board is inside a plastic box on a pole outside.

The second sensor is a friend who lives in the Tropics. They have regular storms. The sensor was working fine for a few weeks before suddenly stopping. The system has been rebooted, checked settings, but strikes are no longer detected.

Both sensors are from Embedded Adventures. I have emailed EA for advice but have not heard anything. Is anyone else having similar issues? I am wondering if we have faulty boards or if we are doing something wrong with the software.

Does anyone know of anything we can try? Is there anyway to test the boards?

**Comment by pcfens** [comment] 2015-01-04 23:55
@jcroucher Have you or your friend gotten your sensors to work?

**Comment by jcroucher** [comment] 2015-01-07 08:48
My friend has detected strikes but has not been home at the time to confirm if they are accurate. It seems to be ok though.
Mine is still not detecting anything. One storm went past, along with one overhead right now.
I restarted everything and got it going during the storm and still nothing detected.

**Comment by merlinmb** [comment] 2015-01-07 08:56
Hi @jcroucher, my embedded adv module also seems to have died & no longer detecting strikes.
I've tried the new reset method, hard rebooting with power reset (luckily easily on a breadboard) - and have confirmed resonating frequency is still at 500khz.

**Comment by pcfens** [comment] 2015-01-07 19:35
I'm going to close this as an issue for now since it seems like any issue that might exist isn't in the library.  - if it turns out to be a problem here then we can re-open it as an active issue.

Feel free to continue discussion here though since others are likely running in to this issue.

Out of curiosity, which version of the Embedded Adventures breakout are you all using?

**Closed by pcfens** 2015-01-07 19:35 UTC
Labels: question

**Comment by jcroucher** [comment] 2015-01-07 23:12
I am using MOD-1016 v6.
